site_name: 'FZU RUN'
site_url: https://run.w2fzu.com/
site_author: west2online
site_description: '福州大学转专业经验站'
nav:
    - 首页: index.md
    - 关于: about.md
    - 计算机:
        # - cs/index.md
        - '[大一]21-土木->计算机类': cs/1.md
        - '[大一]21-环安->计算机类': cs/6.md
        - '[大二]20-机械->计算机类': cs/4.md
        - '[大二]19-生工->计算机类': cs/3.md
        - '[大二]21-生工->软件工程': cs/2.md
        - '[大一]21-土木->软件工程': cs/5.md
        - '[大一]21-土木->软件工程': cs/7.md
        - '[大二]21-材料->软件工程': cs/8.md
    - 数学:
        - '[大一]21-土木->数学类': math/1.md
    - 电气:
        - '[大二]21-土木->电气工程及其自动化': dq/1.md
        - '[大一]21-环安->电气工程及其自动化': dq/2.md
        - '[大一]21-化学->电气工程及其自动化': dq/3.md
    - 物信:
        - '[大一]21-外国语->集成电路设计与集成系统': physics/1.md
    - 外国语:
        - '[大一]21-计算机->英语': sfl/1.md
    - 经管:
        - '[大一]22-外国语->数理金融实验班': jgxy/1.md
        - '[大一]21-机械->数理金融实验班':  jgxy/2.md
        - '[大一]21-土木->经济学': jgxy/3.md
    - 化学:
        - '[大一]22-建筑->嘉锡化学拔尖班':  chem/1.md
    - 资源:
        - 通用:
            - 转专业学生名单公示: source/3.md
        - 法学:
            - 2022法学转专业笔试题目: source/5.md
            - 2022法学转专业面试名单: source/12.md
        - 物信:
            - 2022物信转专业笔试题目: source/6.md
            - 2022物信转专业面试题目: source/7.md
        - 电气:
            - 电气转专业物理复习资料: source/11.md
        - 数学:
            - 2022数学转专业笔试题目: source/10.md
        - 计算机:
            - 2022计算机笔试题目: source/9.md
            - 2022计算机机试题目: source/8.md
            - 计算机简答题整理: source/1.md
            - 20级计算机学院面试名单: source/2.md
            - 21级计算机学院面试名单: source/4.md
theme:
    name: material
    language: zh
    palette:
        primary: white
        accent: blue
    features:
        - navigation.tabs
        # - navigation.indexes
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.expand
        - toc.follow

extra_javascript:
    - 'javascripts/analysis.js'

repo_url: https://github.com/west2-online/fzu-run
repo_name: west2-online/fzu-run